### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
I redesigned these icons to differentiate it from other screen recording apps in the Appcenter, making it more inline with the HIG, and simplifying it to make it less cluttered.
Here's how it looked currently. 
Screenshot from 2020-06-11 20-24-40
image
Screenshot from 2020-06-11 20-26-18

If you liked the current proposal, just give me the go ahead and I'll pixel fit them, otherwise, give me some feedback.

### CODE REVIEW

**Comment by dr-Styki** [comment]
I dunno, I like the fact that the ScreenRec icon look like the Screenshot one. It surely can be improve with a brighter red dot for example. But I don't want something really different for now.
Screenshot from 2020-06-13 09-53-12

**Comment by Fatih20** [comment]
> I dunno, I like the fact that the ScreenRec icon look like the Screenshot one. It surely can be improve with a brighter red dot for example. But I don't want something really different for now.
> Screenshot from 2020-06-13 09-53-12

Ok, I'll look into it then.

**Comment by Fatih20** [comment]
The unused folder in `data/icons/128` is throwaway ideas I made. It's temporary and I'll delete them once the icon is final, but you can look into them should you feel you like one of those ideas and wanted to use them instead.

The screenshot icon have a rounded rectangle with dashed stroke because it's meant to represent "cutting out" a part of the screen using the scissors in the icons, it represents taking a shot of a screen pretty well. However, having that same rounded rectangle with dashed stroke doesn't make sense without the scissors, even more so considering the icon in question doesn't represent taking a shot of the screen. 
So, what I have here is an overlay on a camera's when they're recording a video. Which is 4 corners of a rectangle. Normally, the red circle would be next to one of those corners but I tested that and it looked out of place without the "rec" next to it, which I'm not adding because letters are discouraged by the HIG. So I'm putting front-and-center.

**Comment by dr-Styki** [comment]
Hey, that's really good. I love the new one :heart: 
And you're right about the dashed strokes, the 4 corners of a rectangle make more sense.

**Comment by Fatih20** [comment]
> Hey, that's really good. I love the new one heart
> And you're right about the dashed strokes, the 4 corners of a rectangle make more sense.

Alright, I'll pixel fit them then. 👍️

**Comment by dr-Styki** [comment]
Thank you for this beautiful icon, the PR has been merged :+1:

**Comment by Fatih20** [comment]
> Thank you for this beautiful icon, the PR has been merged +1

Sure thing, just don't forget to credit me in the next release notes.

Also, here's a video of me making the icon.
https://open.lbry.com/@Fatih109:4/Final-Design:6?r=Cg1pp5MCWV1a5Nj5jDumPs9b13dNZqWG
And me making the unused designs, in case you're interested.
https://open.lbry.com/@Fatih109:4/Unused-Designs:2?r=Cg1pp5MCWV1a5Nj5jDumPs9b13dNZqWG

**Comment by dr-Styki** [comment]
Yes of course, I'll credit you in the next release notes and in the README. Once I've fix the twitter https://github.com/dr-Styki/ScreenRec/issues/14 issue, I do that and I publish the new release. :+1:

Videos are good, maybe I can share the one of the final icon with the new release ?

**Comment by Fatih20** [comment]
> Yes of course, I'll credit you in the next release notes and in the README. Once I've fix the twitter #14 issue, I do that and I publish the new release. +1
> 
> Videos are good, maybe I can share the one of the final icon with the new release ?

Thanks, that would be nice of you!

**Pull request merged**
